---
title: "Quick Table1 Report"
author: "Danielle"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: false
    df_print: paged
    theme: flatly
---

# Quick table
```{r}
patient_ds <- open_dataset(file.path(config$tables_path, "clif_patient.parquet")) %>% 
  collect()
hospital_ds <- open_dataset(file.path(config$tables_path, "clif_hospitalization.parquet")) %>% 
  collect()
names(patient_ds)


master_list_demos <- master_list %>% 
  inner_join(hospital_ds %>% select(hospitalization_id, patient_id), by = "hospitalization_id") %>% 
  collect() %>% 
  inner_join(patient_ds %>% select(patient_id, sex_category, race_category, ethnicity_category), by = "patient_id")

```

```{r}
# Define dataset
data_t1 <- master_list_demos %>%
  select(-hospitalization_id, -patient_id, -admission_dttm, -presumed_flag, -wbc_bin)

# Convert ase_flag to labeled factor
data_t1 <- data_t1 %>%
  mutate(ase_flag = factor(ase_flag, levels = c(0, 1),
                           labels = c("No Sepsis", "Sepsis")))

# ----- Create Table 1 -----
table1 <- data_t1 %>%
  tbl_summary(
    by = ase_flag,
    label = list(
      age_at_admission  ~ "Age at Admission (years)",
      wbc_recorded      ~ "White Blood Cell Count (×10⁹/L)",
      temp_recorded     ~ "Temperature (°C)",
      sex_category      ~ "Sex",
      race_category     ~ "Race",
      ethnicity_category ~ "Ethnicity"
    ),
    type = all_dichotomous() ~ "categorical",
    statistic = list(
      all_continuous() ~ "{median} ({p25}, {p75})",
      all_categorical() ~ "{n} ({p}%)"
    ),
    missing = "no"
  ) %>%
  modify_header(label ~ "**Variable**") %>%
  bold_labels()

# add overall column 
table1 <- table1 %>%
  add_overall()

# View the table
table1

```

# Saving table1
```{r}
gtsummary::as_gt(table1) %>%
  gt::gtsave(filename = file.path(config$output_path,"outputs",
                                  paste0(config$site_name, "_table1_", Sys.Date(), ".pdf")))

```


